repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-added-large-files

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.12
  hooks:
    - id: actionlint

- repo: local
  hooks:
    - id: lint-containerfile
      name: Lint Containerfile
      entry: ./build/hadolint-v2.14.0
      language: system
      types: [dockerfile]
      args: ['--failure-threshold', 'warning']

    # TODO(nateinaction): Download fish binary directly when MacOS builds are available in Github
    # which is suppoesed to be soon according to the fish-shell release page: https://github.com/fish-shell/fish-shell/releases/tag/4.8.0
    - id: lint-fish
      name: Check fish config syntax
      entry: fish --no-execute files/skel/.config/fish/config.fish
      language: system
      pass_filenames: false
